import type { RawlinsonsRateItem } from './rawlinsonsTypes';

export const RAWLINSONS_2021_RATES: RawlinsonsRateItem[] = [
  { trade: 'Excavation & Earthworks', item: 'Site excavation light soil', unit: 'cum', rate: 19.6, supplyAndInstall: true },
  { trade: 'Excavation & Earthworks', item: 'Trench excavation 1m deep light soil', unit: 'm', rate: 54.5, supplyAndInstall: true },
  { trade: 'Excavation & Earthworks', item: 'Backfilling with clean sand', unit: 'cum', rate: 58, supplyAndInstall: true },
  { trade: 'Excavation & Earthworks', item: 'Crushed rock filling consolidated', unit: 'cum', rate: 92, supplyAndInstall: true },
  { trade: 'Excavation & Earthworks', item: 'Bored piers 300mm dia', unit: 'm', rate: 96, supplyAndInstall: true },
  { trade: 'Concrete Work', item: '20 MPa concrete base supply', unit: 'cum', rate: 195, supplyAndInstall: false },
  { trade: 'Concrete Work', item: 'Ground slab 100mm thick all-in', unit: 'sqm', rate: 79, supplyAndInstall: true },
  { trade: 'Concrete Work', item: 'Suspended slab 150mm thick', unit: 'sqm', rate: 233, supplyAndInstall: true },
  { trade: 'Concrete Work', item: 'Reinforced concrete wall 150mm thick', unit: 'sqm', rate: 405, supplyAndInstall: true },
  { trade: 'Concrete Work', item: 'Formwork suspended slab Class 3', unit: 'sqm', rate: 129, supplyAndInstall: true },
  { trade: 'Concrete Work', item: 'Reinforcement bar supply and fix', unit: 'tonne', rate: 2720, supplyAndInstall: true },
  { trade: 'Brickwork & Blockwork', item: 'Common clay brick 110mm wall', unit: 'sqm', rate: 130, supplyAndInstall: true },
  { trade: 'Brickwork & Blockwork', item: 'Common clay brick 230mm wall', unit: 'sqm', rate: 260, supplyAndInstall: true },
  { trade: 'Brickwork & Blockwork', item: 'Concrete block 100mm hollow natural', unit: 'sqm', rate: 128.1, supplyAndInstall: true },
  { trade: 'Brickwork & Blockwork', item: 'Concrete block 200mm hollow natural', unit: 'sqm', rate: 144.9, supplyAndInstall: true },
  { trade: 'Brickwork & Blockwork', item: 'Pointing and cleaning one face', unit: 'sqm', rate: 10, supplyAndInstall: true },
  { trade: 'Structural Steel & Metalwork', item: 'Universal beams and columns bolted', unit: 'tonne', rate: 5900, supplyAndInstall: true },
  { trade: 'Structural Steel & Metalwork', item: 'Galvanised steel guardrail', unit: 'm', rate: 103, supplyAndInstall: true },
  { trade: 'Structural Steel & Metalwork', item: 'Duct access panel 600x600mm', unit: 'No', rate: 135, supplyAndInstall: true },
  { trade: 'Carpentry & Timber Framing', item: 'Timber floor framing 150x50 at 450mm', unit: 'sqm', rate: 70.2, supplyAndInstall: true },
  { trade: 'Carpentry & Timber Framing', item: 'Wall framing 100x38 studs at 450mm', unit: 'sqm', rate: 42.4, supplyAndInstall: true },
  { trade: 'Carpentry & Timber Framing', item: 'Roof framing timber up to 10m span', unit: 'sqm', rate: 137, supplyAndInstall: true },
  { trade: 'Carpentry & Timber Framing', item: 'Hardboard flooring 4.8mm', unit: 'sqm', rate: 28.2, supplyAndInstall: true },
  { trade: 'Carpentry & Timber Framing', item: 'Particle board flooring 22mm', unit: 'sqm', rate: 35.6, supplyAndInstall: true },
  { trade: 'Carpentry & Timber Framing', item: 'T&G radiata pine flooring 25mm', unit: 'sqm', rate: 71.2, supplyAndInstall: true },
  { trade: 'Joinery & Cabinetry', item: 'Benchtop laminate HMR substrate', unit: 'sqm', rate: 500, supplyAndInstall: true },
  { trade: 'Joinery & Cabinetry', item: 'Benchtop engineered stone 20mm', unit: 'sqm', rate: 950, supplyAndInstall: true },
  { trade: 'Joinery & Cabinetry', item: 'Floor cupboard unit medium quality 1.2m', unit: 'm', rate: 900, supplyAndInstall: true },
  { trade: 'Joinery & Cabinetry', item: 'Wall-mounted overhead cabinet', unit: 'm', rate: 375, supplyAndInstall: true },
  { trade: 'Windows, Doors & Hardware', item: 'Hollow core door 2040x820mm incl frame', unit: 'No', rate: 475, supplyAndInstall: true },
  { trade: 'Windows, Doors & Hardware', item: 'Solid core door 2040x820mm incl frame', unit: 'No', rate: 530, supplyAndInstall: true },
  { trade: 'Windows, Doors & Hardware', item: 'Glazed timber door single panel', unit: 'No', rate: 1055, supplyAndInstall: true },
  { trade: 'Windows, Doors & Hardware', item: 'Roller door domestic ZINCALUME', unit: 'sqm', rate: 271, supplyAndInstall: true },
  { trade: 'Windows, Doors & Hardware', item: 'Aluminium window domestic standard', unit: 'sqm', rate: 385, supplyAndInstall: true },
  { trade: 'Roofing & Roof Plumbing', item: 'Steel framed roof concrete tiles', unit: 'sqm', rate: 199, supplyAndInstall: true },
  { trade: 'Roofing & Roof Plumbing', item: 'Steel framed roof COLORBOND', unit: 'sqm', rate: 197, supplyAndInstall: true },
  { trade: 'Roofing & Roof Plumbing', item: 'Timber framed roof concrete tiles', unit: 'sqm', rate: 140, supplyAndInstall: true },
  { trade: 'Roofing & Roof Plumbing', item: 'Timber framed roof COLORBOND', unit: 'sqm', rate: 151, supplyAndInstall: true },
  { trade: 'Roofing & Roof Plumbing', item: 'Eaves soffit fibre cement 4.5mm', unit: 'sqm', rate: 114, supplyAndInstall: true },
  { trade: 'Roofing & Roof Plumbing', item: 'Downpipe 100x75mm aluminium', unit: 'm', rate: 34.5, supplyAndInstall: true },
  { trade: 'Wall & Ceiling Linings', item: 'Plasterboard 10mm to timber frame', unit: 'sqm', rate: 31, supplyAndInstall: true },
  { trade: 'Wall & Ceiling Linings', item: 'Plasterboard 13mm fire-rated', unit: 'sqm', rate: 36.8, supplyAndInstall: true },
  { trade: 'Wall & Ceiling Linings', item: 'Fibre cement 6mm Stucco sheet', unit: 'sqm', rate: 59.8, supplyAndInstall: true },
  { trade: 'Wall & Ceiling Linings', item: 'Fibre cement 4.5mm flexible', unit: 'sqm', rate: 34.2, supplyAndInstall: true },
  { trade: 'Wall & Ceiling Linings', item: 'Suspended ceiling 600x600 tiles', unit: 'sqm', rate: 78, supplyAndInstall: true },
  { trade: 'Insulation & Sarking', item: 'Glasswool batts R1.5', unit: 'sqm', rate: 9.2, supplyAndInstall: true },
  { trade: 'Insulation & Sarking', item: 'Glasswool batts R2.0', unit: 'sqm', rate: 9.4, supplyAndInstall: true },
  { trade: 'Insulation & Sarking', item: 'Aluminium foil sarking double sided', unit: 'sqm', rate: 6.4, supplyAndInstall: true },
  { trade: 'Insulation & Sarking', item: 'Polyester batts R2.5', unit: 'sqm', rate: 12.9, supplyAndInstall: true },
  { trade: 'Flooring & Tiling', item: 'Carpet domestic grade with underlay', unit: 'sqm', rate: 45, supplyAndInstall: true },
  { trade: 'Flooring & Tiling', item: 'Vinyl sheet domestic grade', unit: 'sqm', rate: 39, supplyAndInstall: true },
  { trade: 'Flooring & Tiling', item: 'Ceramic tiles 150x150mm PC 29', unit: 'sqm', rate: 107, supplyAndInstall: true },
  { trade: 'Flooring & Tiling', item: 'Quarry tiles 250x250mm PC 33', unit: 'sqm', rate: 111.5, supplyAndInstall: true },
  { trade: 'Flooring & Tiling', item: 'Timber skirting MDF 100x25mm painted', unit: 'm', rate: 21.6, supplyAndInstall: true },
  { trade: 'Painting & Finishes', item: 'Acrylic latex paint smooth 2 coats', unit: 'sqm', rate: 10.05, supplyAndInstall: true },
  { trade: 'Painting & Finishes', item: 'Acrylic semi-gloss paint smooth', unit: 'sqm', rate: 10.9, supplyAndInstall: true },
  { trade: 'Painting & Finishes', item: 'Alkyd enamel paint timber metal', unit: 'sqm', rate: 11.1, supplyAndInstall: true },
  { trade: 'Painting & Finishes', item: 'Wallpaper domestic standard PC 6.50', unit: 'sqm', rate: 21.45, supplyAndInstall: true },
  { trade: 'Sanitary Plumbing & Drainage', item: 'WC Suite plastic cistern PC 435', unit: 'No', rate: 2150, supplyAndInstall: true },
  { trade: 'Sanitary Plumbing & Drainage', item: 'WC Suite vitreous china close coupled', unit: 'No', rate: 2700, supplyAndInstall: true },
  { trade: 'Sanitary Plumbing & Drainage', item: 'Wall Basin modest PC 935', unit: 'No', rate: 2100, supplyAndInstall: true },
  { trade: 'Sanitary Plumbing & Drainage', item: 'Bath 1675mm built in PC 1145', unit: 'No', rate: 2500, supplyAndInstall: true },
  { trade: 'Sanitary Plumbing & Drainage', item: 'Shower general PC 585', unit: 'No', rate: 1900, supplyAndInstall: true },
  { trade: 'Sanitary Plumbing & Drainage', item: 'Kitchen sink 1230mm single bowl', unit: 'No', rate: 2250, supplyAndInstall: true },
  { trade: 'Sanitary Plumbing & Drainage', item: '100mm PVC sewer drain', unit: 'm', rate: 76, supplyAndInstall: true },
  { trade: 'Electrical Services', item: 'Light point residential circuit', unit: 'Point', rate: 105, supplyAndInstall: true },
  { trade: 'Electrical Services', item: 'Power point single residential', unit: 'Point', rate: 105, supplyAndInstall: true },
  { trade: 'Electrical Services', item: 'Power point twin residential', unit: 'Point', rate: 115, supplyAndInstall: true },
  { trade: 'Electrical Services', item: 'Ceiling exhaust fan circuit', unit: 'No', rate: 125, supplyAndInstall: true },
  { trade: 'Electrical Services', item: 'Smoke alarm photoelectric surface', unit: 'Each', rate: 97, supplyAndInstall: true },
  { trade: 'Electrical Services', item: 'Cost per sqm Medium House', unit: 'sqm', rate: 58.75, supplyAndInstall: true },
  { trade: 'Mechanical Services HVAC', item: 'Split system air-conditioning', unit: 'sqm', rate: 108, supplyAndInstall: true },
  { trade: 'Mechanical Services HVAC', item: 'Ducted domestic system zoned', unit: 'sqm', rate: 109, supplyAndInstall: true },
  { trade: 'Mechanical Services HVAC', item: 'Room air-conditioning residential', unit: 'sqm', rate: 56, supplyAndInstall: true },
  { trade: 'External Works & Landscaping', item: 'Concrete paving 100mm thick', unit: 'sqm', rate: 74.6, supplyAndInstall: true },
  { trade: 'External Works & Landscaping', item: 'Brick paving clay on prepared bed', unit: 'sqm', rate: 67.6, supplyAndInstall: true },
  { trade: 'External Works & Landscaping', item: 'Timber fence 1800mm high', unit: 'm', rate: 81, supplyAndInstall: true },
  { trade: 'External Works & Landscaping', item: 'Chain link fence 2100mm high', unit: 'm', rate: 74, supplyAndInstall: true },
  { trade: 'External Works & Landscaping', item: 'Topsoil and lawn 300mm plus turf', unit: 'sqm', rate: 19.7, supplyAndInstall: true },
];