import { cat, catX, type WorkCategory } from '../types';

export const EXTENDED_WALL_CATEGORIES: WorkCategory[] = [
  cat('ceilings', '🏠 Ceilings & Cornices', 'ceilings', 'structural',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Plasterboard repair', 'Bulkhead', 'Raking ceiling', 'New ceiling'] }],
    [{ name: 'Demolition (if req.)', trade: 'Demo', rate: 45, unit: 'area', duration: 1, description: 'Remove existing ceiling' }, { name: 'Frame & Sheet', trade: 'Carpentry', rate: 85, unit: 'area', duration: 2, description: 'Ceiling frame and plasterboard' }, { name: 'Cornice & Finish', trade: 'Carpentry', rate: 35, unit: 'linear', duration: 1, description: 'Cornice, set, and finish' }],
    [], ['All materials and labour', 'Cornice and finishing'], ['Insulation (separate)', 'Asbestos removal'], [{ categoryId: 'painting', type: 'suggested' }, { categoryId: 'insulation', type: 'suggested' }]),
  catX('internalWalls', '🧱 Internal Walls', 'internalWalls', 'structural', 'element',
    [{ id: 'wallType', label: 'Wall construction', type: 'select', options: ['90mm timber stud + plasterboard', '70mm timber stud + plasterboard', '64mm steel stud + plasterboard', '92mm steel stud + plasterboard', 'Single brick (110mm)', 'Double brick cavity (270mm)', 'Hebel block (75mm)'] }, { id: 'finish', label: 'Plasterboard finish', type: 'select', options: ['Standard 10mm', 'Wet-area 10mm (CSR Wet)', 'Acoustic 13mm', 'Fire-rated 13mm'], dependsOn: { questionId: 'wallType', values: ['90mm timber stud + plasterboard', '70mm timber stud + plasterboard', '64mm steel stud + plasterboard', '92mm steel stud + plasterboard'] } }, { id: 'insulation', label: 'Acoustic / thermal insulation', type: 'select', options: ['None', 'R2.0 acoustic batt', 'R2.5 thermal batt', 'R2.7 acoustic + thermal'] }],
    [{ name: 'Frame', trade: 'Carpentry', rate: 85, unit: 'area', duration: 1, description: 'Construct wall frame to specified type' }, { name: 'Insulation install', trade: 'Carpentry', rate: 18, unit: 'area', duration: 0.5, description: 'Friction-fit batt insulation' }, { name: 'Sheet & set', trade: 'Carpentry', rate: 65, unit: 'area', duration: 1, description: 'Plasterboard, set 3-coat finish' }],
    [], ['Frame to specified construction', 'Plasterboard to nominated finish', '3-coat set ready for paint'], ['Painting (separate category)', 'Skirting / architrave (separate category)', 'Electrical chasing & make-good', 'Structural lintels / load-bearing modifications'], [{ categoryId: 'painting', type: 'suggested' }, { categoryId: 'electrical', type: 'suggested' }, { categoryId: 'insulation', type: 'suggested' }], { dimensionMode: 'wall', supportsPcItems: false, contingency: 10, workType: 'renovation' }),
];