import { cat, type WorkCategory } from '../types';

export const KITCHEN_LAUNDRY_CATEGORIES: WorkCategory[] = [
  cat('kitchen', '🍳 Kitchen', 'kitchen', 'wet',
    [{ id: 'size', label: 'Kitchen size', type: 'select', options: ['Small (3x2m)', 'Medium (4x3m)', 'Large (5x4m)', 'Custom'] },
     { id: 'type', label: 'Scope', type: 'select', options: ['Full renovation', 'New kitchen', 'Cabinet replacement'] },
     { id: 'benchtop', label: 'Benchtop', type: 'select', options: ['Laminate', 'Stone (Caesarstone)', 'Porcelain'] }],
    [{ name: 'Demolition & Remove', trade: 'Demo', rate: 2200, unit: 'item', duration: 2, description: 'Strip existing kitchen' },
     { name: 'Plumbing/Electrical Rough-in', trade: 'Plumbing', rate: 2800, unit: 'allow', duration: 2, description: 'Relocate services' },
     { name: 'Plastering & Making Good', trade: 'Plastering', rate: 165, unit: 'area', duration: 2, description: 'Patch walls and ceilings' },
     { name: 'Cabinet Installation', trade: 'Carpentry', rate: 6500, unit: 'allow', duration: 3, description: 'Supply & install cabinetry' },
     { name: 'Benchtop Template & Install', trade: 'Carpentry', rate: 3500, unit: 'allow', duration: 2, description: 'Stone benchtop templating & install' },
     { name: 'Splashback Tiling', trade: 'Tiling', rate: 145, unit: 'area', duration: 1, description: 'Install splashback tiles' },
     { name: 'Plumbing/Electrical Fit-off', trade: 'Electrical', rate: 2200, unit: 'allow', duration: 1, description: 'Connect appliances, lighting' },
     { name: 'Painting', trade: 'Painting', rate: 65, unit: 'area', duration: 2, description: 'Paint walls and ceilings' }],
    [{ description: 'Kitchen Cabinets', allowance: 8000, unit: 'allowance' }, { description: 'Stone Benchtop', allowance: 4000, unit: 'allowance' }, { description: 'Sink & Tapware', allowance: 900, unit: 'set' }, { description: 'Handles & Hardware', allowance: 300, unit: 'allowance' }],
    ['Delivery & installation of cabinetry', 'Standard appliance connections', 'Splashback tiling', 'Making good walls and painting'],
    ['Appliance supply (unless PC)', 'Gas fitting if required', 'Structural alterations', 'Flooring replacement', 'Council/permit fees'],
    [{ categoryId: 'plumbing', type: 'auto' }, { categoryId: 'electrical', type: 'auto' }, { categoryId: 'painting', type: 'suggested' }, { categoryId: 'flooring', type: 'suggested' }]),

  cat('laundry', '🧺 Laundry', 'laundry', 'wet',
    [{ id: 'size', label: 'Laundry size', type: 'select', options: ['Small (2x2m)', 'Medium (3x2m)', 'Large (3x3m)'] },
     { id: 'type', label: 'Scope', type: 'select', options: ['Full renovation', 'New laundry', 'Upgrade'] }],
    [{ name: 'Demolition', trade: 'Demo', rate: 1200, unit: 'item', duration: 1, description: 'Remove existing laundry' },
     { name: 'Plumbing Rough-in', trade: 'Plumbing', rate: 1800, unit: 'allow', duration: 1, description: 'Rough-in new services' },
     { name: 'Waterproofing', trade: 'Waterproofing', rate: 185, unit: 'area', duration: 1, description: 'Membrane to floor' },
     { name: 'Floor & Wall Tiling', trade: 'Tiling', rate: 155, unit: 'area', duration: 2, description: 'Supply & install tiles' },
     { name: 'Cabinetry Install', trade: 'Carpentry', rate: 2500, unit: 'allow', duration: 1, description: 'Install laundry cabinets' },
     { name: 'Plumbing Fit-off', trade: 'Plumbing', rate: 1200, unit: 'allow', duration: 0.5, description: 'Connect tub, taps, trough' }],
    [{ description: 'Tub & Tapware', allowance: 500, unit: 'set' }, { description: 'Cabinetry', allowance: 2000, unit: 'allowance' }, { description: 'Tiles', allowance: 70, unit: '$/m²' }],
    ['AS3740 waterproofing', 'Cabinetry supply & install', 'Plumbing connections'],
    ['Appliance supply', 'Structural work', 'Floor levelling'],
    [{ categoryId: 'waterproofing', type: 'auto' }, { categoryId: 'plumbing', type: 'auto' }, { categoryId: 'cabinetry', type: 'suggested' }]),
];